# Generated by Django 3.2.16 on 2023-02-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_auto_20230227_0349"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ("-created",), "verbose_name": "News", "verbose_name_plural": "News"},
        ),
    ]
